### ISSUE TITLE
有关focusable的接口resetLimitingEl无效的问题

### ISSUE THREAD

**Issue by lwl9710** [slailcp/tv-focusable-example#4]
当我手动去设置弹窗的根元素时也就是赋值limitingEl，我观察到其他非弹窗的"可聚焦"元素的会从focusable状态变成focusdisabled状态，
但是当我关闭弹窗并尝试调用恢复原来焦点的时候，我调用了resetLimitingEl方法,我发现之前的元素还是focusdisabled状态，我观察到这是不正常的，于是我观察了一下被压缩后的代码，修改“a._limitingEl=initData.limitingEl”为“a.limitingEl=initData.limitingEl”就修复了这个问题。(我去掉了前面的"_"字符，我去掉了前面的"_"字符，我去掉了前面的"_"字符,重要的事情说三遍！)

**Comment by slailcp** [comment]
已在vue-tv-focusable@1.1.1版本修复
